version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
    image: slack-memo-bot:v0.0.9
    container_name: memo-bot
    volumes:
      - ../config:/app/config
    environment:
      NODE_ENV: production
    ports:
      - 80:80
