version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
    image: zbbk8sdevelop.azurecr.io/slack-memo-bot:v1.0.4
    container_name: memo-bot
    volumes:
      - ../config:/app/config
    environment:
      NODE_ENV: production
    ports:
      - 10002:10002
